### PR TITLE
Hibernate 4 support

### PR DESCRIPTION
**Pull request by sandyscoffable**
Supports https://github.com/scoffable/scoffable/pull/157

### CODE REVIEW

**Review by MalcolmScoffable — APPROVED** [review]
Yeah, I think this is cool. Kind of hard to see exactly what's going on with the amount of changed files - but it looks as if you are just tidying up the package.

**Review by dej — APPROVED** [review]

**Comment by dej** [comment]
Unable to review 1060 files.  I'm sure it's fine! 👍

**Comment by dej** [comment]
I did look at your new build.gradle file for tapestry-hibernate-core which looks sensible.

**Comment by dej** [comment]
From the Gradle to the Grave 💀 ☠️ 🗡 💀 ☠️ 🗡 💀 ☠️ 🗡

**Pull request merged**
